oes:
  rbac:
    enabled: true
spinnaker:
  authnEnabled: {{ .Values.sapor.config.spinnaker.authnEnabled }}
  baseurl: {{ .Values.sapor.config.spinnaker.spinGateURL }}
  externalBaseUrl: {{ .Values.sapor.config.spinnaker.spinExternalGateURL }}
  ldap:
    enabled: {{ .Values.sapor.config.spinnaker.ldap.ldapEnabled }}
    username: {{ .Values.sapor.config.spinnaker.ldap.ldapUsername }}
    password: {{ .Values.sapor.config.spinnaker.ldap.ldapPassword }}
    adminLoginEnabled: {{ .Values.sapor.config.spinnaker.ldap.ldapAdminLoginEnabled }}
    adminUsername: {{ .Values.sapor.config.spinnaker.ldap.ldapAdminUsername }}
    adminPassword: {{ .Values.sapor.config.spinnaker.ldap.ldapAdminPassword }}
  x509:
    enabled: {{ .Values.sapor.config.spinnaker.x509.enabled }}
    client:
      file: {{ .Values.sapor.config.spinnaker.x509.client.file }}
      password: {{ .Values.sapor.config.spinnaker.x509.client.password }}
spring:
  datasource:
    url: {{ .Values.db.url }}/oesdb
    username: {{ .Values.db.username }}
    password: {{ .Values.db.password }}
datasources:
  platform: {{ .Values.sapor.config.datasources.platform }}
