# OpsMx : 11=Dec-2019
# Sample PV for satisfying the PVC from autopilot-db pod
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-lib-postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: oes-db-postgresql-oes-db-0
    namespace: oes
  hostPath:
    path: "/home/vagrant/PVDIR/LIB-POSTGRESQL"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-master
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: elasticsearch-master-elasticsearch-master-0
    namespace: oes
  hostPath:
    path: "/home/vagrant/PVDIR/ELASTICSEARCH"



