apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-spinnaker-redis-master-0 
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi

