{{- if .Values.spinnaker.gitopsHalyard.pipelinePromotion.enabled }}
apiVersion: v1
data:
  # Git token to access repo where pipeline stuff is stored
  git_secret_token: <git_token_base64_encoded>
kind: Secret
metadata:
  namespace: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.executionNamespace }}
  name: git-token
type: Opaque
{{- end }}
