{{- if .Values.spinnaker.gitopsHalyard.pipelinePromotion.enabled }}
apiVersion: v1
data:
  # Spin CLI config content used by syncToSpinnaker stage
  # It is placed under ~/.spin/config
  # endpoint should be the spinnaker gate where pipelines are created/updated
  config: <content_to_be_put_into_spincli_config_base64_encoded>
kind: Secret
metadata:
  name: local-spin-cli-config
  namespace: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.executionNamespace }}
{{- end }}
